universe = container
initialdir = /home/jcfreeman2/chtc_align/outputs
executable = /home/jcfreeman2/chtc_align/bwa_stampy.pl

# to fix container executable issue
transfer_executable = true

output = bwa_stampy_$(block_id).out
error = bwa_stampy_$(block_id).err
log = bwa_stampy_$(block_id).log
transfer_input_files = /home/jcfreeman2/chtc_align/input_fastq/shared/pipeline_software.tgz,/home/jcfreeman2/chtc_align/input_fastq/shared/$(ref),/home/jcfreeman2/chtc_align/input_fastq/$(fastq1),/home/jcfreeman2/chtc_align/input_fastq/$(fastq2)
when_to_transfer_output = ON_EXIT_OR_EVICT
#+WantFlocking = true
#+WantGlideIn = true

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)
# OSDF file transfer protocol allows for use from non-chtc nodes, but currently not working,
# transfering from staging temporarily
#container_image = osdf:///chtc/staging/jcfreeman2/osgvo-el7.sif
container_image = file:///staging/jcfreeman2/osgvo-el7.sif

request_cpus = 1
#request_disk = 10000000 Jeremy had- but I seem to be using 20% of this with current block size
request_disk = 8000000
stream_output = false
request_memory = 1000
queue 1
