universe = vanilla
initialdir=/home/jcfreeman2/chtc_align/outputs
executable=/home/jcfreeman2/chtc_align/bwa_stampy.pl
output = bwa_stampy_$(block_id).out
error = bwa_stampy_$(block_id).err
log = bwa_stampy_$(block_id).log
transfer_input_files = /home/jcfreeman2/chtc_align/input_fastq/shared/pipeline_software.tgz,/home/jcfreeman2/chtc_align/input_fastq/shared/$(ref),/home/jcfreeman2/chtc_align/input_fastq/$(fastq1),/home/jcfreeman2/chtc_align/input_fastq/$(fastq2)
when_to_transfer_output = ON_EXIT_OR_EVICT
+WantFlocking = true
+WantGlideIn = true
requirements = (OpSys == "LINUX") && (machine != "patel0000.chtc.wisc.edu")
request_cpus = 1
request_disk = 2000000
stream_output = false
request_memory = 1000
queue 1
